baseURL = 'https://arturobermejo.com/'
languageCode = 'en-us'
title = 'Arturo Bermejo'
theme = 'minimal-personal'

# Google Analytics
googleAnalytics = "G-WHHJQJJ3VB"  # Reemplaza con tu ID real

# Pagination (updated format for Hugo v0.128.0+)
[pagination]
  pagerSize = 10
  path = "page"

# Enable syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true

[params]
  math = true
  description = "Personal website and portfolio of Arturo Bermejo"
  author = "Arturo Bermejo"
  email = "your-email@example.com"
  subtitle = "Developer - Musician - Human"
  
  # Blog homepage settings
  blog_title = "Latest Posts"
  blog_description = "Thoughts, insights, and experiences about technology, development, music, and life."
  
  # Profile image (optional)
  profile_image = "/images/profile.jpg"
  
  # Social links
  [[params.social]]
    name = "GitHub"
    url = "https://github.com/arturobermejo"
  
  [[params.social]]
    name = "LinkedIn"
    url = "https://linkedin.com/in/arturobermejo"
  
  [[params.social]]
    name = "Twitter"
    url = "https://twitter.com/arturobermejo"
  
  [[params.social]]
    name = "Email"
    url = "mailto:your-email@example.com"

# Menu configuration (optional - for additional menu items)
# [menu]
#   [[menu.main]]
#     name = "Contact"
#     url = "/contact/"
#     weight = 50

# Markup configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
  [markup.highlight]
    style = "github"
    lineNos = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'